# Generated by Django 5.0.6 on 2024-10-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Independent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('account_type', models.SmallIntegerField(blank=True, choices=[(0, "Boshlang'ich"), (1, "Qo'shimcha ")], null=True)),
            ],
            options={
                'verbose_name': 'Mustaqil ish',
                'verbose_name_plural': 'Mustaqil ishlar',
            },
        ),
        migrations.CreateModel(
            name='Practical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('account_type', models.SmallIntegerField(blank=True, choices=[(0, "Boshlang'ich"), (1, "Qo'shimcha ")], null=True)),
            ],
            options={
                'verbose_name': "Amaliy mashg'ulot",
                'verbose_name_plural': "Amaliy mashg'ulot",
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('account_type', models.SmallIntegerField(blank=True, choices=[(0, "Boshlang'ich"), (1, "Qo'shimcha ")], null=True)),
            ],
            options={
                'verbose_name': 'Taqdimot',
                'verbose_name_plural': 'Taqdimotlar',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('pdf', models.FileField(upload_to='pdf/')),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('account_type', models.SmallIntegerField(blank=True, choices=[(0, "Boshlang'ich"), (1, "Qo'shimcha ")], null=True)),
            ],
            options={
                'verbose_name': 'Maruza',
                'verbose_name_plural': 'Maruza',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='youtube url joylash')),
                ('text', models.TextField(verbose_name='Nima haqida')),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('account_type', models.SmallIntegerField(blank=True, choices=[(0, "Boshlang'ich"), (1, "Qo'shimcha ")], null=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
            },
        ),
    ]
