# Generated by Django 5.0.6 on 2024-05-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='registered_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
