# Generated by Django 5.0.6 on 2024-05-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_subject_registered_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='account_type',
            field=models.CharField(choices=[('E', "Boshlang'ich "), ('A', "Qo'shimcha ")], default='E', max_length=1),
        ),
    ]
