# Generated by Django 5.0.6 on 2024-06-06 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_presentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='img',
        ),
        migrations.AddField(
            model_name='presentation',
            name='video',
            field=models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
