# Generated by Django 5.0.6 on 2024-06-06 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_presentation_img_presentation_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('account_type', models.CharField(choices=[('E', "Boshlang'ich "), ('A', "Qo'shimcha ")], default='E', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='video',
        ),
        migrations.AddField(
            model_name='presentation',
            name='img',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
    ]
