# Generated by Django 5.0.6 on 2024-06-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_video_remove_presentation_video_presentation_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos_uploaded'),
        ),
    ]
