# Generated by Django 5.1 on 2024-09-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='independent',
            options={'verbose_name': 'Mustaqil ish', 'verbose_name_plural': 'Mustaqil ishlar'},
        ),
        migrations.AlterModelOptions(
            name='pdf',
            options={'verbose_name': 'PDF', 'verbose_name_plural': 'PDFLar'},
        ),
        migrations.AlterModelOptions(
            name='practical',
            options={'verbose_name': "Amaliy mashg'ulot", 'verbose_name_plural': "Amaliy mashg'ulot"},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name': 'Taqdimot', 'verbose_name_plural': 'Taqdimotlar'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Maruza', 'verbose_name_plural': 'Maruza'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videolar'},
        ),
        migrations.AlterField(
            model_name='independent',
            name='account_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, "Boshlang'ich"), (1, "Qo'shimcha ")], null=True),
        ),
        migrations.AlterField(
            model_name='practical',
            name='account_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, "Boshlang'ich"), (1, "Qo'shimcha ")], null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='account_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, "Boshlang'ich"), (1, "Qo'shimcha ")], null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='account_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, "Boshlang'ich"), (1, "Qo'shimcha ")], null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='account_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, "Boshlang'ich"), (1, "Qo'shimcha ")], null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=50, verbose_name='youtube url joylash'),
        ),
    ]
