# Generated by Django 5.1 on 2024-09-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_independent_options_alter_pdf_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='img',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
    ]
