# Generated by Django 5.1 on 2024-09-13 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_video_video_video_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.subject'),
            preserve_default=False,
        ),
    ]
