# Generated by Django 5.1 on 2024-09-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_pdf_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
